const CACHE_NAME = 'uhall-oates-v43';
const APP_SHELL = [
  './',
  './index.html',
  './manifest.webmanifest',
  './src/styles/main.css',
  './src/main.js',
  './src/engine/audio.js',
  './src/engine/game.js',
  './src/engine/preloader.js',
  './src/engine/renderer.js',
  './src/engine/state.js',
  './src/engine/save.js',
  './src/ui/ui.js',
  './src/ui/settings.js',
  './src/game-data/registry.js',
  './src/game-data/characters.js',
  './src/game-data/items/item-descriptions.js',
  './src/game-data/audio/audio-manifest.js',
  './src/game-data/debug/debug-loadouts.js',
  './src/game-data/puzzles/registry.js',
  './src/game-data/puzzles/shared/shared-puzzle-overlay.js',
  './src/game-data/puzzles/shared/shared-puzzle-logic-console.js',
  './src/game-data/puzzles/finale/final-puzzle-rhythm-rehearsal.js',
  './src/game-data/puzzles/original/original-puzzle-crane.js',
  './src/game-data/puzzles/original/original-puzzle-wiffle.js',
  './src/game-data/puzzles/original/original-puzzle-voice-mixer.js',
  './src/game-data/puzzles/original/original-puzzle-recall-clause.js',
  './src/game-data/puzzles/original/original-puzzle-storage-directory.js',
  './src/game-data/campaigns/original/original-campaign.js',
  './src/game-data/campaigns/original/chapters/original-chapter-01.js',
  './src/game-data/campaigns/original/chapters/original-chapter-02.js',
  './src/game-data/campaigns/original/chapters/original-chapter-03.js',
  './src/game-data/campaigns/original/chapters/original-chapter-04.js',
  './src/game-data/campaigns/original/chapters/original-chapter-05.js',
  './src/game-data/campaigns/original/chapters/original-chapter-06.js',
  './src/game-data/campaigns/original/chapters/original-chapter-outro.js',
  './src/game-data/campaigns/original/dialogue/original-dialogue-chapter-01.js',
  './src/game-data/campaigns/original/dialogue/original-dialogue-chapter-02.js',
  './src/game-data/campaigns/original/dialogue/original-dialogue-chapter-03.js',
  './src/game-data/campaigns/original/dialogue/original-dialogue-chapter-04.js',
  './src/game-data/campaigns/original/dialogue/original-dialogue-chapter-05.js',
  './src/game-data/campaigns/original/dialogue/original-dialogue-chapter-06.js',
  './src/game-data/campaigns/original/dialogue/original-dialogue-outro.js',
  './src/game-data/campaigns/original/scenes/original-scene-game-complete.js',
  './src/game-data/campaigns/original/scenes/original-scene-london-shipping-depot.js',
  './src/game-data/campaigns/original/scenes/original-scene-luke-wiffle-stadium.js',
  './src/game-data/campaigns/original/scenes/original-scene-manhattan-loading-zone.js',
  './src/game-data/campaigns/original/scenes/original-scene-old-orchard-pier.js',
  './src/game-data/campaigns/original/scenes/original-scene-the-forks-finale.js',
  './src/game-data/campaigns/original/scenes/original-scene-timmins-maxima.js',
  './src/game-data/campaigns/original/scenes/original-scene-tokyo-cargo-district.js',
  './src/game-data/campaigns/adult-relocation/adult-campaign.js',
  './src/game-data/campaigns/adult-relocation/chapters/adult-chapter-01.js',
  './src/game-data/campaigns/adult-relocation/chapters/adult-chapter-02.js',
  './src/game-data/campaigns/adult-relocation/chapters/adult-chapter-03.js',
  './src/game-data/campaigns/adult-relocation/chapters/adult-chapter-04.js',
  './src/game-data/campaigns/adult-relocation/chapters/adult-chapter-05.js',
  './src/game-data/campaigns/adult-relocation/chapters/adult-chapter-06.js',
  './src/game-data/campaigns/adult-relocation/chapters/adult-chapter-07.js',
  './src/game-data/campaigns/adult-relocation/chapters/adult-chapter-outro.js',
  './src/game-data/campaigns/adult-relocation/scenes/adult-scene-helpers.js',
  './src/game-data/campaigns/adult-relocation/scenes/adult-scene-maxima-trunk.js',
  './src/game-data/campaigns/adult-relocation/scenes/adult-scene-reardon-resort.js',
  './src/game-data/campaigns/adult-relocation/scenes/adult-scene-copier-room.js',
  './src/game-data/campaigns/adult-relocation/scenes/adult-scene-mall-concourse.js',
  './src/game-data/campaigns/adult-relocation/scenes/adult-scene-storage-auction.js',
  './src/game-data/campaigns/adult-relocation/scenes/adult-scene-smoothmove-office.js',
  './src/game-data/campaigns/adult-relocation/scenes/adult-scene-daryl-switchboard.js',
  './src/game-data/campaigns/adult-relocation/scenes/adult-scene-john-payphone.js',
  './src/game-data/campaigns/adult-relocation/scenes/adult-scene-michael-conference.js',
  './src/game-data/campaigns/adult-relocation/scenes/adult-scene-fractured-warehouse.js',
  './src/game-data/campaigns/adult-relocation/scenes/adult-scene-restored-depot.js',
  './src/game-data/campaigns/finale/final-campaign.js',
  './src/game-data/campaigns/finale/chapters/final-chapter-01.js',
  './src/game-data/campaigns/finale/chapters/final-chapter-02.js',
  './src/game-data/campaigns/finale/chapters/final-chapter-03.js',
  './src/game-data/campaigns/finale/chapters/final-chapter-04.js',
  './src/game-data/campaigns/finale/chapters/final-chapter-05.js',
  './src/game-data/campaigns/finale/chapters/final-chapter-06.js',
  './src/game-data/campaigns/finale/chapters/final-chapter-outro.js',
  './src/game-data/campaigns/finale/scenes/final-scene-helpers.js',
  './src/game-data/campaigns/finale/scenes/final-scene-depot-anniversary.js',
  './src/game-data/campaigns/finale/scenes/final-scene-listening-room.js',
  './src/game-data/campaigns/finale/scenes/final-scene-chicago-studio.js',
  './src/game-data/campaigns/finale/scenes/final-scene-commercial-studio.js',
  './src/game-data/campaigns/finale/scenes/final-scene-rehearsal-tent.js',
  './src/game-data/campaigns/finale/scenes/final-scene-pier-concert.js',
  './src/game-data/campaigns/finale/scenes/final-scene-morning-depot.js',
  './src/game-data/campaigns/finale/songs/youre-doing-it.js',
  './assets/app-icons/app-icon-192.png',
  './assets/app-icons/app-icon-512.png',
  './assets/app-icons/app-icon-maskable-1024.png',
  './assets/social/uhall-oates-social-card-v2.png',
  './assets/art/ui/uhall-oates-truck-logo-v2.png',
  './assets/art/ui/20th-something-anniversary-badge-v1.png',
  './assets/art/ui/character-headshot-tile-v1.png',
  './assets/art/ui/inventory-sprites-v1.png',
  './assets/art/campaigns/original/reveals/hall-oates-crawl-reveal-v1.png',
  './assets/art/campaigns/original/reveals/chapter-01-old-orchard-v1.png',
  './assets/art/campaigns/original/reveals/chapter-02-manhattan-v1.png',
  './assets/art/campaigns/original/reveals/chapter-03-jacuzzi-park-v1.png',
  './assets/art/campaigns/original/reveals/chapter-04-london-v1.png',
  './assets/art/campaigns/original/reveals/chapter-05-tokyo-v1.png',
  './assets/art/campaigns/original/reveals/chapter-06-the-forks-v1.png',
  './assets/art/campaigns/original/chapters/chapter-01/old-orchard-pier-v1.png',
  './assets/art/campaigns/original/chapters/chapter-01/old-orchard-pier-gull-gone-v1.png',
  './assets/art/campaigns/original/chapters/chapter-02/1987-baseball-card-pack-v1.png',
  './assets/art/characters/john-oates-worried-v1.png',
  './assets/art/characters/john-oates-determined-v1.png',
  './assets/art/characters/john-oates-relieved-v1.png',
  './assets/art/characters/john-oates-startled-v1.png',
  './assets/art/characters/john-oates-frustrated-v1.png',
  './assets/art/characters/huey-lewis-alarmed-v1.png',
  './assets/art/characters/michael-mcdonald-delighted-v1.png',
  './assets/art/characters/baltos-breakthrough-v1.png',
  './assets/art/characters/daryl-hall-relieved-v1.png',
  './assets/art/characters/jamo-impressed-v1.png',
  './assets/art/characters/luke-jacuzzi-excited-v1.png',
  './assets/art/characters/jesse-reardon-furious-v1.png',
  './assets/art/characters/joe-reardon-rattled-v1.png',
  './assets/art/characters/joe-timmins-smug-v1.png',
  './assets/art/characters/michael-bolton-sprite-v1.png',
  './assets/art/characters/kenny-loggins-sprite-v1.png',
  './assets/art/characters/young-joe-timmins-sprite-v1.png',
  './assets/art/campaigns/adult-relocation/chapters/adult-01/maxima-trunk-v1.png',
  './assets/art/campaigns/adult-relocation/chapters/adult-02/reardon-resort-v1.png',
  './assets/art/campaigns/adult-relocation/chapters/adult-02/copier-room-v1.png',
  './assets/art/campaigns/adult-relocation/chapters/adult-03/mall-concourse-v1.png',
  './assets/art/campaigns/adult-relocation/chapters/adult-04/storage-auction-v1.png',
  './assets/art/campaigns/adult-relocation/chapters/adult-05/smoothmove-office-v1.png',
  './assets/art/campaigns/adult-relocation/chapters/adult-06/time-call-v1.png',
  './assets/art/campaigns/adult-relocation/chapters/adult-07/fractured-warehouse-v1.png',
  './assets/art/campaigns/adult-relocation/chapters/adult-outro/restored-depot-v1.png',
  './assets/art/campaigns/adult-relocation/reveals/adult-01-maxima-trunk-v1.png',
  './assets/art/campaigns/adult-relocation/reveals/adult-02-danger-zone-v1.png',
  './assets/art/campaigns/adult-relocation/reveals/adult-03-mall-v1.png',
  './assets/art/campaigns/adult-relocation/reveals/adult-04-storage-auction-v1.png',
  './assets/art/campaigns/adult-relocation/reveals/adult-05-smoothmove-v1.png',
  './assets/art/campaigns/adult-relocation/reveals/adult-06-touch-tone-v1.png',
  './assets/art/campaigns/adult-relocation/reveals/adult-07-timeline-v1.png',
  './assets/art/campaigns/finale/chapters/final-01/depot-anniversary-v1.png',
  './assets/art/campaigns/finale/chapters/final-02/listening-room-v1.png',
  './assets/art/campaigns/finale/chapters/final-03/chicago-studio-v1.png',
  './assets/art/campaigns/finale/chapters/final-04/commercial-studio-v1.png',
  './assets/art/campaigns/finale/chapters/final-05/rehearsal-tent-v1.png',
  './assets/art/campaigns/finale/chapters/final-06/pier-concert-v1.png',
  './assets/art/campaigns/finale/chapters/final-outro/morning-depot-v1.png',
  './assets/art/campaigns/finale/chapters/final-outro/hall-oates-performance-v1.png',
  './assets/art/campaigns/finale/items/bent-spool-v1.png',
  './assets/art/campaigns/finale/items/blank-cue-card-v1.png',
  './assets/art/campaigns/finale/items/broadcast-route-card-v1.png',
  './assets/art/campaigns/finale/items/clean-live-mix-v1.png',
  './assets/art/campaigns/finale/items/damaged-rehearsal-reel-v1.png',
  './assets/art/campaigns/finale/items/full-rehearsal-mix-v1.png',
  './assets/art/campaigns/finale/items/label-2008-v1.png',
  './assets/art/campaigns/finale/items/purpose-receipt-v1.png',
  './assets/art/campaigns/finale/items/rehearsal-route-board-v1.png',
  './assets/art/campaigns/finale/items/restored-rehearsal-reel-v1.png',
  './assets/art/campaigns/finale/items/set-list-fragment-v1.png',
  './assets/art/campaigns/finale/items/shared-arrangement-v1.png',
  './assets/art/campaigns/finale/items/sound-blanket-v1.png',
  './assets/art/campaigns/finale/items/studio-patch-cable-v1.png',
  './assets/audio/music/title-original.mp3',
  './assets/audio/music/chapter-01-original.mp3',
  './assets/audio/music/chapter-02-original.mp3',
  './assets/audio/music/chapter-03-original.mp3',
  './assets/audio/music/chapter-04-original.mp3',
  './assets/audio/music/chapter-05-original.mp3',
  './assets/audio/music/chapter-06-original.mp3',
  './assets/audio/music/outro-original.mp3',
  './assets/audio/music/adult-01-original.mp3',
  './assets/audio/music/adult-02-original.mp3',
  './assets/audio/music/adult-03-original.mp3',
  './assets/audio/music/adult-04-original.mp3',
  './assets/audio/music/adult-05-original.mp3',
  './assets/audio/music/adult-06-original.mp3',
  './assets/audio/music/adult-07-original.mp3',
  './assets/audio/music/adult-outro-original.mp3',
  './assets/audio/music/final-01-original.mp3',
  './assets/audio/music/final-02-original.mp3',
  './assets/audio/music/final-03-original.mp3',
  './assets/audio/music/final-04-original.mp3',
  './assets/audio/music/final-05-original.mp3',
  './assets/audio/music/final-06-original.mp3',
  './assets/audio/music/final-outro-original.mp3',
  './assets/audio/music/youre-doing-it.mp3',
  './assets/audio/sfx/pickup.wav',
  './assets/audio/sfx/success-chime.wav',
  './assets/audio/sfx/crane-motor.wav',
  './assets/audio/sfx/repair-ratchet.wav',
  './assets/audio/sfx/prize-drop.wav',
  './assets/audio/sfx/gull-squawk.wav',
  './assets/audio/sfx/paper-rustle.wav',
  './assets/audio/sfx/stamp-thunk.wav',
  './assets/audio/sfx/cards-rip.wav',
  './assets/audio/sfx/scoreboard-beeps.wav',
  './assets/audio/sfx/wiffle-launch.wav',
  './assets/audio/sfx/customs-clack.wav',
  './assets/audio/sfx/route-whoosh.wav',
  './assets/audio/sfx/lift-unlock.wav',
  './assets/audio/sfx/capsule-rotate.wav',
  './assets/audio/sfx/voice-glitch.wav',
  './assets/audio/sfx/broadcast-surge.wav',
  './assets/audio/sfx/contract-shred.wav',
  './assets/audio/sfx/tape-rip.wav',
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(APP_SHELL)));
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET' || new URL(event.request.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request).then((response) => {
        // Range requests for audio return 206 responses, which the Cache API
        // cannot store. Cache only complete responses and await the write so a
        // rejected cache operation never becomes an unhandled promise.
        if (response.status === 200) {
          const copy = response.clone();
          return caches.open(CACHE_NAME)
            .then((cache) => cache.put(event.request, copy))
            .catch(() => undefined)
            .then(() => response);
        }
        return response;
      }).catch(() => {
        if (event.request.mode === 'navigate') return caches.match('./index.html');
        return new Response('Offline asset unavailable', { status: 503, statusText: 'Offline' });
      });
    }),
  );
});
